### ISSUE TITLE
Caffeine tekort

### ISSUE THREAD

**Issue by fiechtor** [fiechtor/solitaire-student-version#4]
ik heb koffie nodig

**Comment by PepijnBeukjema** [comment]
Hallo Fiechtor,

Bedankt voor je reactie! Ik wil je erop attenderen dat je op de 3e verdieping van de haagse hogeschool in Den Haag koffie kunt halen, ook staat er op elke verdieping tenminste 2 koffie dispensers. (Deze bevatten ook chocolademelk/cacao en soep!) Let op, want dit kost allemaal geld. Als je 'gratis' koffie wilt dan verzoek ik dat je thuis wat drinkt. Als je verder nog vragen hebt dan horen wij het graag.

Mvg,

FiechterFighter
(Pepijn Beukema)

**Comment by fiechtor** [comment]
Hoi Pepijn!

Bedankt voor je antwoord. Ik ga even kijken.

MVG,

Beautje de beunhaas
